# Generated by Django 4.0.6 on 2023-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
